<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>XYZBankFlow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>07317f92-75d8-4fdf-8ec1-f60246dc4991</testSuiteGuid>
   <testCaseLink>
      <guid>2ca22e75-f176-4129-9e2a-660e7830cd5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Deposit/TC01_AmountDeposit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>38bcfc59-f1bc-47ae-985f-5b4b491aba76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC01_LoginTest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ac089f-7dfe-4e02-84e3-b9e27e1e616e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fb6718c-a791-4f6a-b438-724ba31fccdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Withdraw/TC01_WithdrawExcessAmountTest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>978a6503-5f39-410d-ae78-8ce3c85239a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0156e6b1-15b4-411f-9fd6-e217b9026872</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Withdraw/TC01_WithdrawTest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f0656f8-f096-441e-954f-f95c7c16b35b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
